# Site settings
author: Amy Fong
title: Software Engineering at Flatiron School
header-img: img/home-bg.png
email: amyhfong@gmail.com
copyright_name: Amy Fong
description: > # this means to ignore newlines until "baseurl:"
  Blog about learning how to code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AmyFong82

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
